trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

- script: |
    python -m ensurepip
    python -m pip install --upgrade pip
    pip install ansible
  displayName: 'Install Ansible'

- task: GitCheckout@2
  inputs:
    repository: 'https://github.com/tonymishler/ansible_demo.git'
    clean: true
    fetchDepth: 1
    path: 'ansible_demo'
  displayName: 'Checkout Ansible Playbook'

- script: |
    ansible-playbook ansible_demo/playbook.yml
  displayName: 'Run Ansible Playbook'
