trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: 'app_user'
    value: 'myappuser'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

- script: |
    python -m ensurepip
    python -m pip install --upgrade pip
    pip install ansible
  displayName: 'Install Ansible'

- script: |
    git clone --depth 1 https://github.com/tonymishler/ansible_demo.git ansible_demo
  displayName: 'Checkout Ansible Playbook'

- script: |
    ansible-playbook ansible_demo/playbook.yml -e app_user="${{ variables.app_user }}"

