---
- name: Install required packages on a machine
  hosts: localhost #specifies to run locally
  connection: local 
  become: yes # will execute with elevated prileges
  become_method: sudo #the method that Ansible should use to become the superuser
  become_user: anthonymishler #the user to act as when performing super user tasks
  gather_facts: no # don't gather machine information for this script 
  # vars:
  #   remote_tmp: /tmp
  #   local_tmp: /tmp


  tasks:
  - name: Check if Xcode Command Line Tools are installed
    command: xcode-select -p
    #changed_when: false
    register: xcode_tools_result
    ignore_errors: yes

  - name: Install Xcode Command Line Tools
    command: xcode-select --install
    when: xcode_tools_result.rc != 0

  - name: Check if Homebrew is installed
    command: brew --version
    #changed_when: false
    register: homebrew_result
    ignore_errors: yes

  - name: Install Homebrew
    shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    when: homebrew_result.rc != 0

  - name: Set Homebrew ownership
    become: yes
     #ansible_user is predefined 
    shell: chown -R "{{ ansible_user }}:admin" /usr/local/Homebrew
    when: homebrew_result.rc != 0

  - name: Check if Powershell is installed
    command: pwsh -v
    #changed_when: false
    register: powershell_result
    ignore_errors: yes

  - name: Install Powershell
    shell: brew install --cask powershell
    when: powershell_result.rc != 0

  - name: Check if Ruby and related packages are installed
    command: ruby --version && gem --version
    #changed_when: false
    register: ruby_result
    ignore_errors: yes

  - name: Install Ruby and related packages
    shell: |
      curl -sSL https://get.rvm.io | bash
      source ~/.rvm/scripts/rvm
      rehash
      rvm install 3.1.3
      gem update
      gem update --system
      gem install compass
    when: ruby_result.rc != 0

  - name: Check if .NET 6 and 7 are installed
    shell: dotnet --version
    #changed_when: false
    register: dotnet_result
    ignore_errors: yes

  - name: Install .NET 6 and 7 using Homebrew
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - dotnet-sdk-6.0
      - dotnet-sdk-7.0
    when: dotnet_result.rc != 0

  - name: Check if AWS CLI is installed
    command: aws --version
    #changed_when: false
    register: awscli_result
    ignore_errors: yes

  - name: Install AWS CLI
    shell: |
      curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
      sudo installer -pkg AWSCLIV2.pkg -target /
    when: awscli_result.rc != 0

  - name: Check if fnm is installed
    command: fnm --version
    #changed_when: false
    register: fnm_result
    ignore_errors: yes

  - name: Install fnm and Node 16
    shell: |
      curl -fsSL https://fnm.vercel.app/install | bash
      fnm install 16
    when: fnm_result.rc != 0

  - name: Verify Node installation
    command: node --version
    register: node_version
    #changed_when: false
    failed_when: node_version.rc != 0
    check_mode: no

  - name: Check if Python is installed
    command: python -V
    #changed_when: false
    register: python_result
    ignore_errors: true
    failed_when: python_result.rc not in [0, 2]


  - name: Install Python with Homebrew
    homebrew:
      name: python
      state: present
    when: python_result.rc != 0

