- name: Uninstall packages and tools
  hosts: localhost #specifies to run locally
  connection: local 
  become: yes # will execute with elevated prileges
  become_method: sudo #the method that Ansible should use to become the superuser
  become_user: testuser
  gather_facts: no # don't gather machine information for this script 
  # vars:
  #   remote_tmp: /tmp
  #   local_tmp: /tmp

  tasks:

  - name: Uninstall Powershell
    shell: brew uninstall --cask powershell
    ignore_errors: yes

  - name: Uninstall Ruby and related packages
    shell: |
      rvm implode
      gem uninstall compass
    ignore_errors: yes

  - name: Uninstall .NET 6 and 7 using Homebrew
    homebrew:
      name: "{{ item }}"
      state: absent
    with_items:
      - dotnet-sdk-6.0
      - dotnet-sdk-7.0
    ignore_errors: yes

  - name: Uninstall AWS CLI
    shell: sudo rm -rf /usr/local/aws /usr/local/awscli /usr/local/bin/aws
    ignore_errors: yes

  - name: Uninstall fnm and Node 16
    shell: |
      fnm use system
      fnm implode
    ignore_errors: yes

